name: ShulkerPacks
version: 1.5.1
main: me.darkolythe.shulkerpacks.ShulkerPacks
api-version: 1.13
softdepend: [WorldGuard, GriefPrevention]

permissions:
  shulkerpacks.use:
    description: gives player permission to open shulker boxes in their inventory
    default: op